"""Notes, contacts and attachments on tiles and areas (HLR-10). Adds tables only; existing data is untouched.

Revision ID: 0002_details
Revises: 0001_baseline
Create Date: 2026-09-29 14:15:46.502646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_details'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stored_name', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(category_id IS NULL) <> (area_id IS NULL)', name='ck_attachments_one_owner'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_category_id'), ['category_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('organisation', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phones', sa.JSON(), nullable=False),
    sa.Column('phone_digits', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(category_id IS NULL) <> (area_id IS NULL)', name='ck_contacts_one_owner'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_category_id'), ['category_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(category_id IS NULL) <> (area_id IS NULL)', name='ck_notes_one_owner'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_category_id'))
        batch_op.drop_index(batch_op.f('ix_notes_area_id'))

    op.drop_table('notes')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_category_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_area_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_category_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_area_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
